name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install and build with Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - run: yarn install
    - run: yarn build
